### ISSUE TITLE
Ajout d'une liste résumant tous les élèves placés sur le Canvas, visible depuis le canvas et la table des attributs

### ISSUE THREAD

**Issue by ThomasLecluse** [wawachief/SalleDeClasse#53]

**Comment by ThomasLecluse** [comment]
"Recyclage" de la liste des élèves (deuxième onglet du side-widget), lorsque le mode "config" est activé. C'est donc la liste des étudiants visibles qui y est affiché

**Comment by wawachief** [comment]
done
