### ISSUE TITLE
Taille de fenêtre supérieure à la taille d'écran

### ISSUE THREAD

**Issue by jmclem** [wawachief/SalleDeClasse#81]
**Contexte** : SdC 1.0.0 démarré depuis le AppImage, LUbuntu 18.04, résolution d'écran 1366x768 (ordinateur portable)

**Problème** : La fenêtre principale de l'application est plus grande que l'affichage du bureau et ne se laisse pas redimensionner ; les icônes et onglets situés en bas de la fenêtre de l'application sont invisibles. 

**Workaround** : déplacer la fenêtre avec ALT + Mouse click-move pour accéder aux contrôles.

**Suggestion** : pouvoir redimensionner la fenêtre.

**Comment by ThomasLecluse** [comment]
Bonjour,

L'application possède une taille minimale du fait de la taille des bureaux dans la salle de classe. Elle peut être redimensionnée tant que la dimension est supérieure ou égale à cette dimension minimale.

Une autre chose que vous pouvez essayer est de changer les paramètres de la section **[size]** du fichier _.SdCrc_ (situé dans votre home) :

- Le paramètre **desk** permet de régler la taille (en pixels) des bureaux (qui sont carrés, par défaut 65px de côté). Attention, une taille trop petite rendrait l'affichage des noms des élèves tronqué.
- Les paramètres **default_room_rows** et **default_room_columns** désignent respectivement le nombre de lignes et de colonnes de la grille de la salle de classe. Peut-être pouvez-vous les diminuer si jamais vous travaillez dans des salles n'étant pas si grandes (par défaut 11*13).


Faites-nous savoir si cela vous convient. Nous discuterons de la possibilité de redimensionner sous la taille minimale ; toutefois, je pense que cela pourrait rendre l'affichage incohérent dans certains cas, à voir.

Merci d'utiliser Salle De Classe !

**Comment by jmclem** [comment]
J'ai changé 
```
default_room_rows = 9
default_room_columns = 11
```

qui me suffisent largement (petites salles ;) ), j'ai maintenant toute l'appli sur un écran sans devoir déplacer.

Autre suggestion : ne pas gérer les espaces comme des carrés, mais comme des rectangles.

On peut fermer ceci pour ma part, à vous de voir si le redimensionnement de fenêtre est une fonctionnalité à inclure.

Merci pour le taf !

**Comment by ThomasLecluse** [comment]
Ravi que cela vous convienne dans ce cas !

Je vais créer une autre issue pour la gestion des bureaux en tant que rectangles au lieu de carrés, c'est un sujet dont nous avions brièvement parlé, mais que nous pourrions explorer plus en détails ;)

Merci à vous d'utiliser Salle de Classe,
Bonne continuation.
